[package]
name = "moonshot"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
anyhow = "1.0.93"
indoc = "1.0"
lalrpop-util = { version = "0.22.0", features = ["lexer"] }
